### PR TITLE
MeetupsAdd: Fix time validation (fixes #4928)

### LINKED ISSUE #4928: MeetupsAdd: End time validation regression

### PR DESCRIPTION
**Pull request by paulbert**
#4928

### CODE REVIEW

**Comment by lmmrssa** [comment]
When trying to make multi day to single day event, it is not allowing to make end date empty. End time is validating fine.

File: src/app/validators/custom-validators.ts [hunk 1]
```diff
@@ -112,7 +100,7 @@ export class CustomValidators {
       }
 
       // if start date has not been given a value yet return back
-      if (!startDate) {
+      if (!startDate || !endDate.value) {
```
Comment (paulbert) [inline src/app/validators/custom-validators.ts]: This should do to allow the end date to be blank after it has been given a value.

Comment (paulbert) [reply src/app/validators/custom-validators.ts]: @lmmrssa
