### PR TITLE
5672 edit header and message is now fixed (fixes #5672)

### LINKED ISSUE #5672: TeamsViewFinancesComponent: Edit Transaction header and message
**Steps to replicate**
1. Go to enterprise
2. Add transaction
3. Try to edit Transaction

The header of dialog form shows **Add Transaction**.

Screenshot from 2020-01-31 15-07-28

&nbsp;
&nbsp;
&nbsp;
After Editing Transaction error message shows **Transaction Added**

&nbsp;
&nbsp;
&nbsp;
Screenshot from 2020-01-31 15-11-35

### PR DESCRIPTION
**Pull request by gyawaliamit7**
Screen Shot 2020-02-06 at 12 27 06 AM

Screen Shot 2020-02-06 at 12 27 10 AM

### CODE REVIEW

File: src/app/teams/teams-view-finances.component.ts [hunk 1]
```diff
@@ -125,11 +125,19 @@ export class TeamsViewFinancesComponent implements OnInit, OnChanges {
           date: [ transaction.date ? new Date(new Date(transaction.date).setHours(0, 0, 0)) : new Date(time), CustomValidators.required ]
         },
         {
-          onSubmit: (newTransaction) => this.submitTransaction(newTransaction, transaction).subscribe(() => {
-            this.planetMessageService.showMessage('Transaction added');
+          onSubmit: (newTransaction) => {
+            if (!transaction._id) {
```
Comment (paulbert) [inline src/app/teams/teams-view-finances.component.ts]: Please refactor this to reduce the repetition.

File: src/app/teams/teams-view-finances.component.ts [hunk 2]
```diff
@@ -125,11 +125,19 @@ export class TeamsViewFinancesComponent implements OnInit, OnChanges {
...
+              this.submitTransaction(newTransaction, transaction).subscribe(() => {
+              this.planetMessageService.showMessage('Transaction Added');
+              });
+            } else {
+              this.submitTransaction(newTransaction, transaction).subscribe(() => {
+              this.planetMessageService.showMessage('Transaction Edited');
+              });
+            }
             this.dialogsFormService.closeDialogsForm();
```
Comment (paulbert) [inline src/app/teams/teams-view-finances.component.ts]: This line was called in the subscription, now it is called before the subscription completes.

Please make sure after making changes that this happens after `submitTransaction` completes.

File: src/app/teams/teams-view-finances.component.ts [hunk 3]
```diff
@@ -125,11 +125,19 @@ export class TeamsViewFinancesComponent implements OnInit, OnChanges {
...
-          onSubmit: (newTransaction) => this.submitTransaction(newTransaction, transaction).subscribe(() => {
-            this.planetMessageService.showMessage('Transaction added');
+          onSubmit: (newTransaction) => {
+            if (!transaction._id) {
+              this.submitTransaction(newTransaction, transaction).subscribe(() => {
+              this.planetMessageService.showMessage('Transaction Added');
+              });
+            } else {
+              this.submitTransaction(newTransaction, transaction).subscribe(() => {
+              this.planetMessageService.showMessage('Transaction Edited');
```
Comment (paulbert) [inline src/app/teams/teams-view-finances.component.ts]: As a note any time a new block begins indentation should increase by 2 spaces.

After your refactor there should no longer be this level of indentation, but I wanted to note this for future reference.

File: src/app/teams/teams-view-finances.component.ts [hunk 4]
```diff
@@ -125,19 +125,13 @@ export class TeamsViewFinancesComponent implements OnInit, OnChanges {
...
-              this.planetMessageService.showMessage('Transaction Added');
-              });
-            } else {
-              this.submitTransaction(newTransaction, transaction).subscribe(() => {
-              this.planetMessageService.showMessage('Transaction Edited');
-              });
-            }
+          onSubmit: (newTransaction) => this.submitTransaction(newTransaction, transaction).subscribe(() => {
+            var message ='';
+            transaction._id ? message = 'Updated': message = 'Added';
```
Comment (paulbert) [inline src/app/teams/teams-view-finances.component.ts]: Ternary expressions are not a good place for side effects.  The expression should act like a function that returns one value or the other based on a condition.  That value can then be assigned to a variable or used as a function parameter.

File: src/app/teams/teams-view-finances.component.ts [hunk 5]
```diff
@@ -125,19 +125,13 @@ export class TeamsViewFinancesComponent implements OnInit, OnChanges {
...
-              this.submitTransaction(newTransaction, transaction).subscribe(() => {
-              this.planetMessageService.showMessage('Transaction Added');
-              });
-            } else {
-              this.submitTransaction(newTransaction, transaction).subscribe(() => {
-              this.planetMessageService.showMessage('Transaction Edited');
-              });
-            }
+          onSubmit: (newTransaction) => this.submitTransaction(newTransaction, transaction).subscribe(() => {
+            var message ='';
```
Comment (paulbert) [inline src/app/teams/teams-view-finances.component.ts]: We've completely shifted to `let` or `const` ES6 variable declarations.  `const` should be used if the variable's value never changes.
