### PR TITLE
 login: smoother dialog behaviour (fixes #8432) 

### LINKED ISSUE #8432: erratic behaviour when login page is first accessed
In production systems, navigating directly to the login page (e.g., https://planet.learning.ole.org/eng/login) and then manually removing the 'login' segment from the URL incorrectly displays the login popup, rather than showing the open community page as expected.

### PR DESCRIPTION
**Pull request by paulbert**
Trying a fix for the login dialog not quite following the expected behavior based on beta settings. Because that issue has only been seen in production need to test with the docker image built for this PR.

### CODE REVIEW

**Comment by paulbert** [comment]
I think this is ready. To test pull this as a production docker image with

```
docker pull treehouses/planet-tags:0.17.77-8432-beta-then-auth-wait-for-configuration-ff94a3fb
docker tag treehouses/planet-tags:0.17.77-8432-beta-then-auth-wait-for-configuration-ff94a3fb treehouses/planet:local
```

From unlogged in you should see
- localhost:3300/ => community page
- localhost:3300/resources => blank page with login dialog

Also it'd be good to test the case of logging in, logging out, open a new window and then test the above. There was a report of strange behavior with that.

**Review by jessewashburn — CHANGES_REQUESTED** [review]
Initially, it worked as expected, but when I was at the login page on one tab and navigated to localhost:3300 on another, I got this weird blank login screen 

image

From then on, localhost:3300 kept redirecting me to http://localhost:3300/eng/login 

Tried restarting the containers but that did not fix the issue.

File: src/app/shared/beta-then-auth-guard-service.ts [hunk 1]
```diff
@@ -11,14 +14,24 @@ export class BetaThenAuthService {
...
-    if (this.userService.isBetaEnabled() === true) {
-      return of(true);
-    }
-    return this.authService.canActivateChild(route, state);
+    return iif(
+      () => this.stateService.configuration?._id !== undefined,
+      of(true),
+      this.stateService.couchStateListener('configurations')
+    ).pipe(switchMap((res) => {
+      console.log(`BetaThenAuth: ${res}`);
```
Comment (paulbert) [inline src/app/shared/beta-then-auth-guard-service.ts:27]: Leaving these console log lines in for help with testing. Go ahead and remove before merging if it's ready.

**Comment by paulbert** [comment]
I think I got it now. At least it's ready to test again.

**Comment by Mutugiii** [comment]
New image to test
```
docker pull treehouses/planet-tags:0.17.77-8432-beta-then-auth-wait-for-configuration-2eb4ba20
docker tag treehouses/planet-tags:0.17.77-8432-beta-then-auth-wait-for-configuration-2eb4ba20
```

**Review by Mutugiii — APPROVED** [review]

**Review by jessewashburn — CHANGES_REQUESTED** [review]
Tested with the new image, but I'm still getting the grey background and am having issues having the community page be reachable by default once I reach the grey screen that session. Please let me know if I'm doing something wrong.

[recording(2).webm](https://github.com/user-attachments/assets/9fa5ba69-21e0-4ea5-81fe-8c24b1cc594e)

**Review by jessewashburn — APPROVED** [review]

**Comment by jessewashburn** [comment]
Might have been a caching issue, as I can no longer replicate. We can just keep an eye out for it.

**Review by dogi — APPROVED** [review]
