### PR TITLE
Fix initial columns (fixes #6816)

### LINKED ISSUE #6816: mySubmissions: Initial columns incorrect
Graded on column is hidden for My Sumbission -> Survey.
1.But Go to Survey tab -> click on any survey detail page -> back
2. now graded on column start showing in Survey tab as well.
3. switch to Test tab and then switch back to Survey
4. Now graded on column disappears.

https://recordit.co/7SUu6fT3tA

### PR DESCRIPTION
**Pull request by Haoran-Hu**
Fixes #6816 

Still has a routing problem. Click on a survey and go back, the page goes to **Tests** submissions.

### CODE REVIEW

File: src/app/submissions/submissions.component.ts [hunk 1]
```diff
@@ -69,7 +69,7 @@ export class SubmissionsComponent implements OnInit, AfterViewChecked, OnDestroy
 
   ngOnInit() {
     this.setMode();
-    this.filter.type = this.route.snapshot.paramMap.get('type') || 'exam';
+    this.onFilterChange(this.filter.type, 'type');
```
Comment (paulbert) [inline src/app/submissions/submissions.component.ts:72]: The filter should be set to `this.route.snapshop.paramMap.get('type') || 'exam'`, not itself.
