### PR TITLE
fixed spinner( Fixed 4954)

### LINKED ISSUE #4954: TeamsView: When removing member spinner opens under dialog
There should not be a spinner opening below the dialog.  A spinner is only needed after **OK** is clicked to remove the member.

https://www.loom.com/share/da7ce366da904dcc8ebb3d6e88a6eb4a

### PR DESCRIPTION
**Pull request by wanglihe2010**
fixed #4954 

I moved the spinner in `changeMembershipRequest` function to `changeMembership` function. 

Adding `leader` is not related to this issue, but it should be an error.

### CODE REVIEW

File: src/app/teams/teams-view.component.ts [hunk 1]
```diff
@@ -236,20 +236,20 @@ export class TeamsViewComponent implements OnInit, AfterViewChecked, OnDestroy {
   changeMembershipRequest(type, memberDoc?) {
     const changeObject = this.changeObject(type, memberDoc);
     return () => {
-      this.dialogsLoadingService.start();
       return changeObject.obs.pipe(
         switchMap(() => type === 'added' ? this.teamsService.removeFromRequests(this.team, memberDoc) : of({})),
         switchMap(() => this.getMembers()),
         switchMap(() => this.sendNotifications('added')),
         map(() => changeObject.message),
-        finalize(() => this.dialogsLoadingService.stop())
```
Comment (paulbert) [inline src/app/teams/teams-view.component.ts]: Please keep this in the `finalize` operator.  This will ensure the dialog closes even if there is an error.
