### PR TITLE
TeamsView: deleted teams fix (fixes #4399)

### LINKED ISSUE #4399: Deleted team is accessible through Notification link
- Click on any deleted team from notification list.
- it will open deleted team profile and user can perform any action.
Screenshot from 2019-07-23 07-46-13

### PR DESCRIPTION
**Pull request by perryc85**

### CODE REVIEW

File: src/app/teams/teams-view.component.ts [hunk 1]
```diff
@@ -135,9 +139,6 @@ export class TeamsViewComponent implements OnInit, OnDestroy {
           onNext: () => {
             this.leaveDialog.close();
             const msg = 'left';
-            if (this.team.status === 'archived') {
```
Comment (lmmrssa) [inline src/app/teams/teams-view.component.ts]: this section is there to redirect after leave button is trigger on team view.

Comment (perryc85) [reply src/app/teams/teams-view.component.ts]: Thank you for the feedback. Will make changes.

Comment (perryc85) [reply src/app/teams/teams-view.component.ts]: @lmmrssa - The code was added back to that section.
